### ISSUE TITLE
OUTI: Kirjastopalvelun tietueiden yhdistymisongelma ja katoavat osakohteet

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/KohaSuomiServices#12]
Oulun luetteloinnista Heikkisen Antti raportoi seuraavasta ongelmasta:

Siirtoraportilla 26.1.2024 klo 14.31 aikoihin on mennyt useampi tietue keskeytyneisiin virheilmoituksella:
Internal Server Error {"errors":[{"message":"Internal Server Error.","path":"\/"}],"status":500}

Nämä kaikki ovat osakohteita lasten CD-levyistä Vauhtiviulujen sormilaulut (FI-BTJ: 7440446) ja Musiikkimatkan soiva vuosi (FI-BTJ: 7331143).

Tällaista on tapahtunut aikaisemminkin eli kyseessä on tapaus, jossa tilataan aineistoa, jolla ei ole varsinaista standardinumeroa, jolla yhdistää tietueita. Jos tietokannassa sattuu jo olemaan jostakin nimekkeestä aiempi tietue, niin uusi hankintatietue ei osaa yhdistyä siihen ja muodostaa tuplan. Tässä ei olisi muuten mitään, jos tuo aiempikin tietue olisi hankintatietue, mutta nyt olikin niin, että se oli valmis tietue osakohteineen. Tällöin käy niin, että kun uusi hankintatietue saapuu uutena tietueena tietokantaan eikä osaa yhdistyä tuohon aiempaan, sen päälle valuu TäTistä oma, uusi täystietue osakohteineen, mutta koska tietokannasta löytyy jo tuo edellinen saman nimekkeen täystietue osakohteineen, niin Mikropalvelu hylkää kokonaan nuo uuden tietueen valuvat osakohteet.

Yleensä sitten käy niin, että kummallakin tietueella näkyy perustiedot-näytöllä tuon aiemman tietueen osakohteet, koska molemmilla tietueilla on samat arvot 001- ja 003-kentässä, Mutta nyt ei käynyt niin, vaan osakohteet ovat kadonneet tuolta ensimmäiseltäkin tietueelta. Tällaista on ehkä tapahtunut aiemminkin, mutta en ole välttämättä kiinnittänyt siihen niin olennaisesti huomiota. Näkyisiköhän jostakin lokista tai tietuehistoriasta, mitä oikein on tapahtunut? Tämä ongelma taitaa koskettaa ainoastaan standarditunnuksettomia osakohteellisia tietueita. Olisikohan mitään keinoa täsmäyttää tietueita, joilla ei ole 020- tai 024-kentässä mitään tunnuksia, jotta vastaavaa ei tapahtuisi? Kirjastopalvelun tietueet saisi kiinni ainakin 035a-kentän tai 001–003-kenttien yhdistelmän kautta.

Vauhtiviulujen sormilaulut -CD (FI-BTJ: 7440446):
Oulun aiempi tietue: 2336033 
Raahen uusi tietue: 2340730

Musiikkimatkan soiva vuosi -CD (FI-BTJ: 7331143):
Oulun aiempi tietue: 2276928
Raahen uusi tietue: 2340734

**Comment by AnttHeik** [comment]
Yritin toistaa virhettä OUTIn testillä Musiikkimatkan soiva vuosi -CD:llä. Toin ensin TäTistä yhden tietueen (OUTI-test-ID: 2335759)  ja valutin sille osakohteet. Tein sitten siitä kopion OUTIin (ID: 2335785), vaihdoin tasoksi varalta 8 ja poistin joitakin tietoja. Tietue aktivoitui samolla arvoilla kuin tuo ensin tehtykin eli 001: FI-BTJ & 003: 7331143, mutta se ei reagoinut mitenkään edes siihen, kun tallensin tietueen uudelleen TäTissä. Tallennuksen seurauksena tiedot valuivat uudestaan vain tuon ensimmäisen tietuee päälle.

Molemmilla tietuiella näkyy osakohteet, koska ne linkittyvät tuosta ensimmäisestä tietueesta myös tuohon toiseen, koska niillä on samat arvot 003- ja 773w-kentissä.
