### ISSUE TITLE
[Bugi] KohaSuomiServices-mikropalveluun ei pääse kirjautumaan, jos TäTi-tunnuksen salasanassa on erikoismerkki

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/KohaSuomiServices#2]
### Mikä vikana?

[KohaSuomiServices-mikropalveluun](https://tati.koha-suomi.fi/service) ei pääse kirjautumaan, jos TäTi-tunnuksen salasanassa on erikoismerkki. Käyttöohjeen mukaan kirjautumaan pitäisi pystyä TäTi-tunnuksella, jolla on superlibrarian-oikeus.

### Mitä pitäisi tapahtua

Pitäisi päästä kirjautumaan sillä salasanalla, millä TäTiinkin.

### Kuinka toistaa ongelma/asia

Vaihda superlibrarian-oikeuksilla olevalle TäTi-tunnukselle salasana, joka sisältää erikoismerkin ja koita kirjautua mikropalveluun.

**Comment by emta001** [comment]
Mitä tämä odottaa?

**Comment by AnneliO** [comment]
> Mitä tämä odottaa?

Johannan paluuta töihin?

**Comment by emta001** [comment]
> > Mitä tämä odottaa?
> 
> Johannan paluuta töihin?

Ehkäpä :D

**Comment by johannaraisa** [comment]
En nyt laita tähän paukkuja ku tarkoitus on siirtää mikropalvelun ominaisuudet koha-plugin-broadcast-biblios-liitännäiseen.

**Comment by PiaKusmin** [comment]
Ongelma koskee myös ääkkösiä.
