### ISSUE TITLE
[Bugi] Osakohteiden valutuksessa Tätistä paikalliskantoihin ongelmia

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/KohaSuomiServices#3]
### Mikä vikana?

Oulun luetteloinnista tuli pyyntö tutkia alla kuvattuja valutuksen ongelmia, joita alkaa olla jo häiritsevän paljon OUTIssa.

Kaikki uudet osakohteet eivät aina valu oikein TäTistä paikalliskantoihin, vaan osa osakohteista tai joskus myös kaikki osakohteet jäävät valumatta. Nämä valumatta jääneet osakohteet näkyvät siirtoraportissa Keskeytyneet-välilehdellä ja useimmiten virheviestinä on "Aborting! Newer export added", vaikka mitään uusia osakohteita ei ole kuitenkaan valunut tietokantaan. Näitä tulee yleensä päivittäin. Osalle uusista tietueista valuu osakohteet ihan oikein, mutta välissä on aina emotietueita, joille ei valunut yhtään osakohdetta.

Myöskin osakohteiden päivitykset menevät useasti keskeytyneisiin, varsinkin sellaiset, joiden päivitys tulee Melindasta asti. Näitä on välillä niin tuhottoman paljon, että menee ihan liian kauan aikaa selvitellä, oliko näillä oikeasti tarvetta valua vai onko kyseessä vaan tavallaan ”turha” (yleensä aikaleiman) päivitys, jolloin ei niin paljon haittaa, vaikka päivitykset eivät paikalliskantoihin asti tulleetkaan. Välissä voi kuitenkin olla tarpeellisiakin päivityksiä, jotka jäävät sitten huomaamatta.

Olisiko mahdollista tutkia, miksi tässä käy niin usean tietueen kohdalla näin? Vaikka noita pelkkiä aikaleimapäivityksiä tulee Melindasta välillä hurjan paljon, olisi kuitenkin hyvä, jos kaikki tietueet päivittyisivät oikein.

### Kohan osio

Kuvailu

**Comment by CodoDerDritte** [comment]
Yksi ongelmista taitaa olla se, että nuo aikaleimapäivitykset aiheuttavat aivan yhtälailla tietueen valumiseen kaikkiin paikalliskantoihin kun kaikki muutkin tietuemuutokset. Kun tämmöisiä ei-olennaisia muutoksia kertyy valutusjonoon isoja määriä, venyy "oikeiden" muutosten saaminen valutukseen asti. Jonojen kasvaessa valutukset venyvät pikkutunneille asti, jolloin käynnissä voi olla jo Koha-installaatioiden yölliseen ylläpitoon liittyviä huoltotoimenpiteitä. Esimerkiksi indeksin varmuuskopiointi näyttää nyt aiheuttavan yövalutuksessa ongelmia, koska hakukone (ElasticSearch) on paikalliskannoista sen aikaa pois käytöstä eikä valutettujen tietueiden indeksointi silloin onnistu (katso tiketti KohaSuomi/koha-plugin-exporter-report#1). Varmuuskopioinnin aikaan tietueita siis varmasti ainakin kopsahtelee virheisiin.
