### ISSUE TITLE
[Bugi] Osakohteille ei tule aineistotyyppi

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/KohaSuomiServices#4]
### Mikä vikana?

Vaarassa on esimerkiksi uusi kirja 24 yötä jouluun (https://vaara.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=11673755&searchid=scs_1667907236277), jolle on tullut Tätistä kuvailutiedot ja osakohteet. Osakohteille ei ole tullut 942c-kenttään aineistotyyppiä. Emme tiedä, onko tällaisia virheellisyyksiä useitakin ja milloin se on alkanut. Tätissä osakohteilla on aineistotyyppi Artikkeli.

### Mitä pitäisi tapahtua

Osakohteille pitäisi tulla emon mukainen aineistotyyppi.

### Kohan osio

Kuvailu

**Comment by AnttHeik** [comment]
Tämä ongelma on ollut olemassa siitä asti, kun valutus otettiin käyttöön. Johanna Räisä sitä yritti mielestäni tutkia, muttei saanut selville, missä vika. 

Versiopäivityksen jälkeen minusta ongelma on vähän parantunut, mutta edelleen näitä tulee vastaan säännöllisen epäsäännöllisesti. Yleensä aineistotyyppi jää puuttumaan n. 1-7 ensimmäiseltä osakohteelta ja näitä tulee aina silloin kun osakohteet valuvat automaattisesti. 

Jos käyttää Perustiedot-näytön Vie/Tuo-nappia, niin silloin aineistotyyppi yleensä muodostuu kaikkiin osakohteisiin. Tosin joskus jos tietokannassa on vain epämääräinen hankintatietue, niin voi olla, ettei aineistotyyppi muodostu silloinkaan. Jos taas emotietue on jo ihan täystietue, niin aineistotyyppi näyttäisi muodostuvan varmemmin.

Tuo osakohteiden aineistotyyppi haetaan siis emon 942c-kentästä ja se tulee sama kaikille osakohteille, vaikka osakohde olisi eri tyyppiä, esim. CD-äänilevy, jonka liitteenä on DVD-levy. Johanna taisi joskus ehdotella, että pitäisikö tehdä jokin takautuva tietokanta-ajo, jolla näitä korjattaisiin, jos vikaa ei saa muuten korjattua. Onko mahdollista, ettei jostain syystä Mikropalvelu saa jostain tuota 942c-kentän tietoa osakohteita tuodessaan, vaikka kentän tieto näyttäisi tietueessa olevankin?

**Comment by AnttHeik** [comment]
Tähän vielä sellainen lisäys, että jos sattuu olemaan sellainen emotietue, jolla on osakohteita, joilla on eri aineistotyyppi, esim. CD-levyllä CD-osakohteiden lisäksi DVD-osakohteita, ja on vaihtanut valutuksen jälkeen Kohan aineistotyypin oikeaksi DVD-osakohteisiin, niin jos käy niin, että tietueeseen valuu päivityksiä jälkeenpäin, DVD-osakohteet vaihtuvat takaisin CD-osakohteiksi, jolloin ne joutuu taas vaihtamaan uudelleen. Olisi hyvä, jos nämä aineistotyypit saisi pysymään jotenkin, ettei niitä tarvitsisi aina uudestaan vaihdella.

**Comment by pknuuti** [comment]
Aineistotyypittömiä osakohteita näyttää tulevan koko ajan. Tämä on kiusallista, jos tekee nimekehaun, jonka rajaa aineistotyypin mukaan, niin eihän ne osakohteet tule hakutulokseen.

**Comment by AnneliO** [comment]
Tällä viikolla otettiin käyttöön Auto Framework Code -liitännäinen, joka valitsee automaattisesti tietueelle aineistotyypin. Onko sen käyttöönotto auttanut tähän ongelmaan?

**Comment by AnttHeik** [comment]
Uusi tietuesiirtäjä auttaa aika hyvin tähän ongelmaan.
