### ISSUE TITLE
[Bugi] Mikropalveluun kirjautuminen ei onnistu

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/KohaSuomiServices#5]
### Mikä vikana?

Jos yrittää kirjautua KohaSuomiServices-mikropalveluun osoitteessa https://tati.koha-suomi.fi/service, tulee vain sininen tausta ja välilehden otsikossa lukee "Server error". Itse olen käyttänyt palvelua viimeksi viime viikolla (vko 44) ja ongelma huomattiin viikon 45 päivityksen jälkeen.

### Mitä pitäisi tapahtua

Sivulla pitäisi tulla näkyville kirjautumisruutu, johon kirjaudutaan TäTi-tunnuksilla.

**Comment by CodoDerDritte** [comment]
Näköjään daemoneja ei voi ajaa supistetummin oikeuksin. Palveluun pääsee nyt jälleen kirjautumaan. Korjailen uutta käynnistysskriptiä kunhan tässä ehdin.

**Comment by CodoDerDritte** [comment]
Skriptin korjattu versio on otettu käyttöön 15.11. (KohaSuomiServices https://github.com/KohaSuomi/KohaSuomiServices/issues/6) ja palveluun kirjautuminen toimii nyt oikein.
