### ISSUE TITLE
Melindan endpoint urlien vaihtaminen  

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/KohaSuomiServices#7]
### Tukipyyntö

Melindan endpoint urlit vaihtuvat uuden REST version myötä. Kohan päässä tämä tarkoittaa, että TäTin asetuksiin  (servicen puolella) on käytävä tekemässä muutokset seuraaviin endpointeihin:

- Melinda/REST/update
- Melinda/REST/add 
- Melinda/REST/get 

Uusiin urleihin voi ottaa mallia TäTin testin puolelta (tiputtaa vain urlista "-test" pois).

**Comment by lmstrand** [comment]
Vaihto tehty tänään Täti-tuotantoon ja endpointit testattu toimiviksi Melinda-porukan kanssa.
