### ISSUE TITLE
Mikropalveluun mahdolliseksi 4-tason tietueen vienti 3-tason Melinda-tietueen päälle

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/KohaSuomiServices#9]
### Kehitysehdotukseni

Mikropalveluun pitäisi tehdä sellainen korjaus, että 4-tason tietueen voi viedä 3-tason Melinda-tietueen päälle. Melindassa näyttää olevan jonkin verran ns. ennakkotietueita, joiden taso on 3, koska niitä on ilmeisesti käsitelty aavistuksen 5-tasoa enemmän saapumisvalvonnassa. Nyt ei esim. voi ottaa Melindasta 3-tason Viola-tietuetta, täydentää sitä TäTissä ja viedä takaisin. Muistini mukaan Mikropalvelussa on edelleen päällä rajaus, jossa numeroarvoltaan suurempaa tasoa ei voi viedä pienemmän päälle, mikä on toisaalta hyvä asia, mutta näissä 4- vs. 3-tason tietueissa ja, jos osakohteissa haluaisi vaihtaa 4-tason 7-tasoksi, niin tämä on vähän ongelmallinen.

### Jotain muuta?

Kehitysehdotus tuli Antti Heikkiseltä.

**Comment by johannaraisa** [comment]
Mikropalvelusta on tarkoitus luopua versiopäivityksessä ja sen kanssa kehitys on jäässä. Olen siirtämässä vientiominaisuuksia Tietuesiirtäjä-liitännäiseen, tämä ominaisuus voidaan lisätä mukaan liitännäiseen.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 5.2.2024: Toteutetaan Tietuesiirtäjä-liitännäiseen.
